### ISSUE TITLE
Specific file type

### ISSUE THREAD

**Issue by AbouJalal** [koltyakov/sp-build-tasks#12]
Hi,

Thanks for this awesome library. I'm just wondering how do you specify to push only certain type of files from your "dist" folder.

**Comment by koltyakov** [comment]
Hey @AbouJalal,

Thank you for your feedback!

Watch and publish tasks grab all files with `**/*.*` pattern, so everything in `dlRootFolder` (by default it's `./dist` folder) publishes to SharePoint.

I'm wondering what is your use case?

**Comment by AbouJalal** [comment]
I want to push all templates that i have in my display templates library.
I can't push all the files that are in my dist because i have a js file associated with each html file.
Usually, SP will create and associate the js file automatically.
No need for some kind of a workaround as i already have couple of workarounds.
I just want to know if there is a way to teach gulp to push only the html files?

**Comment by koltyakov** [comment]
The easiest way to do it is using custom tasks in `./build/tasks` folder.
Custom task's file is a .js file with any name in that folder and a specific pattern.
This can be a good point to start with:

```javascript
module.exports = (gulp, $) => {

    gulp.task('push-html', [ 'config' ], () => {
        let configs = global.gulpConfigs;
        return gulp
            .src([ './dist/**/*.html' ], { base: configs.watch.base })
            .pipe($.spsave(configs.spSaveCoreOptions, configs.privateConf.creds));
    });

    gulp.task('watch-html', [ 'config' ], () => {
        let configs = global.gulpConfigs;
        $.watch([ './dist/**/*.html' ], (event) => {
            console.log(event.path);
            gulp.src(event.path, {
                base: configs.watch.base
            }).pipe(
                $.spsave(
                    configs.spSaveCoreOptions,
                    configs.privateConf.creds
                )
            );
        });
    });

};
```

**Comment by koltyakov** [comment]
Closing this. Feel free to reopen if you still have questions.
