### ISSUE TITLE
SCSS conversion for all files

### ISSUE THREAD

**Issue by clechner77** [koltyakov/sp-build-tasks#2]
Would be incredibly helpful if any scss file in  /src/styles would be automatically compiled and uploaded on watch.

**Comment by koltyakov** [comment]
Hi Clint,

Yep, I was thinking about adding a configuration to allow not only single bundles for TS and SCSS, but also a set of different entry points scripts.
At this point, it's only possible to define one entry point for TypeScript and SCSS. Or adding an ad-hoc task.

Let me think how to enhance this.
Ideas are welcome.

**Comment by koltyakov** [comment]
Hi Clint (@clechner77),

I've added support for multiple endpoints for SCSS files.
Now, it's possible to define the following settings in `./config/app.json`:

```json
{
  ...
  "customStyles": [{
    "src": "styles/app1.scss",
    "dist": "styles/app1.css"
  }, {
    "src": "styles/app2.scss",
    "dist": "styles/app2.css"
  }],
 ...
}
```

Where `customStyles` can be an object or array of objects with `src` and `dist` properties.
Please let me know if you have any questions.

**Comment by koltyakov** [comment]
Closing this. Please reopen in case of questions.
