### ISSUE TITLE
Change stream for errors

### ISSUE THREAD

**Issue by Zilo676** [koltyakov/sp-build-tasks#34]
Hello @koltyakov thanks for this awesome lib.

I am using this tools in my gitlab ci pipelines and have unexpected behavior. When my webpack bundle have errors i want to stop my pipelines. Most runners check stderr stream for a stop pipelines and mark them failed. So i want to change output stream webpack build task from stdout to stderr only for errors

I cam make pr if you wish

**Comment by koltyakov** [comment]
Thanks! Please PR.
