### ISSUE TITLE
Please update es5-ext dependency to avoid spreading political agenda

### ISSUE THREAD

**Issue by AKrasheninnikov** [koltyakov/sp-build-tasks#70]
Currently the referenced version contains an unnecessary post-installation postinstall.js script.

**Comment by koltyakov** [comment]
Hey @AKrasheninnikov,

A PR is welcomed.

**Comment by koltyakov** [comment]
Bumped the dependencies. Now the latest es5-ext version should be installed via lock requirements.

![image](https://user-images.githubusercontent.com/7816483/191614675-41b0db28-6057-4443-a07f-8ecacb97c7b6.png)
 
Please check if sp-build-tasks@3.18.3 has no post install messages which bothered you.
